//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int ID { get; set; }
        public double DLD { get; set; }
        public double DSP { get; set; }
        public double DSD { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
